---
# SPDX-FileCopyrightText: 2025 The Linux Foundation
# SPDX-License-Identifier: Apache-2.0

name: 'Release Drafter'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  # pull_request is required for autolabeler
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  # pull_request_target is required for autolabeler on PRs from forks
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions: {}

concurrency:
  # yamllint disable-line rule:line-length
  group: "rd-${{ github.event_name }}-${{ github.event.number }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  update_release_draft:
    name: 'Update Release Draft'
    permissions:
      # write permission is required to create releases
      contents: write
      # write permission is required for autolabeler
      pull-requests: write
    runs-on: 'ubuntu-latest'
    timeout-minutes: 3
    # yamllint disable rule:line-length
    steps:
      # Harden the runner used by this workflow
      - uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: 'audit'

      - name: 'Show concurrency group'
        shell: bash
        # yamllint disable rule:line-length
        run: |
          # Show concurrency group
          {
            echo '## Release Drafter'
            echo "Concurrency group: rd-${{ github.event_name }}-${{ github.event.number }}-${{ github.ref }}"
          } >> "$GITHUB_STEP_SUMMARY"
          echo "Concurrency group: rd-${{ github.event_name }}-${{ github.event.number }}-${{ github.ref }}"

      - name: 'Update draft release'
        uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
